=begin
#Bullet Train Test

#You can update this description in `config/locales/en/application.en.yml`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BulletTrainTest::GoalsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GoalsApi' do
  before do
    # run before each test
    @api_instance = BulletTrainTest::GoalsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GoalsApi' do
    it 'should create an instance of GoalsApi' do
      expect(@api_instance).to be_instance_of(BulletTrainTest::GoalsApi)
    end
  end

  # unit tests for delete_goals_id
  # Delete a Goal
  # @param id Goal ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_goals_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_goal
  # Retrieve a Goal
  # @param id Goal ID
  # @param [Hash] opts the optional parameters
  # @return [ApiV1GoalSerializer]
  describe 'get_goal test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_goals_id
  # Update a Goal
  # @param id Goal ID
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [ApiV1GoalSerializer]
  describe 'put_goals_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
