=begin
#Bullet Train Test

#You can update this description in `config/locales/en/application.en.yml`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BulletTrainTest::ScaffoldingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ScaffoldingApi' do
  before do
    # run before each test
    @api_instance = BulletTrainTest::ScaffoldingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScaffoldingApi' do
    it 'should create an instance of ScaffoldingApi' do
      expect(@api_instance).to be_instance_of(BulletTrainTest::ScaffoldingApi)
    end
  end

  # unit tests for delete_v1_scaffolding_absolutely_abstract_creative_concepts_id
  # Delete a Creative Concept
  # @param id Creative Concept ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_v1_scaffolding_absolutely_abstract_creative_concepts_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_v1_scaffolding_completely_concrete_tangible_things_id
  # Delete a Tangible Thing
  # @param id Tangible Thing ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_v1_scaffolding_completely_concrete_tangible_things_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_scaffolding_absolutely_abstract_creative_concepts_absolutely_abstract_creative_concept_id_completely_concrete_tangible_things
  # List Tangible Things
  # @param absolutely_abstract_creative_concept_id Creative Concept ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<ApiV1ScaffoldingCompletelyConcreteTangibleThingSerializer>]
  describe 'get_v1_scaffolding_absolutely_abstract_creative_concepts_absolutely_abstract_creative_concept_id_completely_concrete_tangible_things test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_scaffolding_absolutely_abstract_creative_concepts_id
  # Retrieve a Creative Concept
  # @param id Creative Concept ID
  # @param [Hash] opts the optional parameters
  # @return [ApiV1ScaffoldingAbsolutelyAbstractCreativeConceptSerializer]
  describe 'get_v1_scaffolding_absolutely_abstract_creative_concepts_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_scaffolding_completely_concrete_tangible_things_id
  # Retrieve a Tangible Thing
  # @param id Tangible Thing ID
  # @param [Hash] opts the optional parameters
  # @return [ApiV1ScaffoldingCompletelyConcreteTangibleThingSerializer]
  describe 'get_v1_scaffolding_completely_concrete_tangible_things_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_scaffolding_absolutely_abstract_creative_concepts_absolutely_abstract_creative_concept_id_completely_concrete_tangible_things
  # Add a New Tangible Thing
  # @param absolutely_abstract_creative_concept_id Creative Concept ID
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [ApiV1ScaffoldingCompletelyConcreteTangibleThingSerializer]
  describe 'post_v1_scaffolding_absolutely_abstract_creative_concepts_absolutely_abstract_creative_concept_id_completely_concrete_tangible_things test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_v1_scaffolding_absolutely_abstract_creative_concepts_id
  # Update a Creative Concept
  # @param id Creative Concept ID
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [ApiV1ScaffoldingAbsolutelyAbstractCreativeConceptSerializer]
  describe 'put_v1_scaffolding_absolutely_abstract_creative_concepts_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_v1_scaffolding_completely_concrete_tangible_things_id
  # Update a Tangible Thing
  # @param id Tangible Thing ID
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [ApiV1ScaffoldingCompletelyConcreteTangibleThingSerializer]
  describe 'put_v1_scaffolding_completely_concrete_tangible_things_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
