=begin
#OpenAPI Petstore

#This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BulletTrainTest::SuperUserApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SuperUserApi' do
  before do
    # run before each test
    @api_instance = BulletTrainTest::SuperUserApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SuperUserApi' do
    it 'should create an instance of SuperUserApi' do
      expect(@api_instance).to be_instance_of(BulletTrainTest::SuperUserApi)
    end
  end

  # unit tests for delete_user
  # Delete user
  # This can only be done by the logged in user.
  # @param username The name that needs to be deleted
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_user test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
