=begin
#Bullet Train Test

#You can update this description in `config/locales/en/application.en.yml`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BulletTrainTest::WebhooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @api_instance = BulletTrainTest::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@api_instance).to be_instance_of(BulletTrainTest::WebhooksApi)
    end
  end

  # unit tests for delete_v1_webhooks_outgoing_endpoints_id
  # Delete a Endpoint
  # @param id Endpoint ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_v1_webhooks_outgoing_endpoints_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_webhooks_outgoing_deliveries_delivery_id_delivery_attempts
  # List Delivery Attempts
  # @param delivery_id Delivery ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<ApiV1WebhooksOutgoingDeliveryAttemptSerializer>]
  describe 'get_v1_webhooks_outgoing_deliveries_delivery_id_delivery_attempts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_webhooks_outgoing_deliveries_id
  # Retrieve a Delivery
  # @param id Delivery ID
  # @param [Hash] opts the optional parameters
  # @return [ApiV1WebhooksOutgoingDeliverySerializer]
  describe 'get_v1_webhooks_outgoing_deliveries_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_webhooks_outgoing_delivery_attempts_id
  # Retrieve a Delivery Attempt
  # @param id Delivery Attempt ID
  # @param [Hash] opts the optional parameters
  # @return [ApiV1WebhooksOutgoingDeliveryAttemptSerializer]
  describe 'get_v1_webhooks_outgoing_delivery_attempts_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_webhooks_outgoing_endpoints_endpoint_id_deliveries
  # List Deliveries
  # @param endpoint_id Endpoint ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<ApiV1WebhooksOutgoingDeliverySerializer>]
  describe 'get_v1_webhooks_outgoing_endpoints_endpoint_id_deliveries test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_webhooks_outgoing_endpoints_id
  # Retrieve a Endpoint
  # @param id Endpoint ID
  # @param [Hash] opts the optional parameters
  # @return [ApiV1WebhooksOutgoingEndpointSerializer]
  describe 'get_v1_webhooks_outgoing_endpoints_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_v1_webhooks_outgoing_endpoints_id
  # Update a Endpoint
  # @param id Endpoint ID
  # @param [Hash] opts the optional parameters
  # @option opts [UNKNOWN_BASE_TYPE] :unknown_base_type 
  # @return [ApiV1WebhooksOutgoingEndpointSerializer]
  describe 'put_v1_webhooks_outgoing_endpoints_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
