=begin
#Bullet Train Test

#You can update this description in `config/locales/en/application.en.yml`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BulletTrainTest::ApiV1ScaffoldingCompletelyConcreteTangibleThingSerializerData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BulletTrainTest::ApiV1ScaffoldingCompletelyConcreteTangibleThingSerializerData do
  let(:instance) { BulletTrainTest::ApiV1ScaffoldingCompletelyConcreteTangibleThingSerializerData.new }

  describe 'test an instance of ApiV1ScaffoldingCompletelyConcreteTangibleThingSerializerData' do
    it 'should create an instance of ApiV1ScaffoldingCompletelyConcreteTangibleThingSerializerData' do
      expect(instance).to be_instance_of(BulletTrainTest::ApiV1ScaffoldingCompletelyConcreteTangibleThingSerializerData)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "attributes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "relationships"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
