=begin
#Bullet Train Test

#You can update this description in `config/locales/en/application.en.yml`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BulletTrainTest::ApiV1WebhooksOutgoingDeliverySerializer
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BulletTrainTest::ApiV1WebhooksOutgoingDeliverySerializer do
  let(:instance) { BulletTrainTest::ApiV1WebhooksOutgoingDeliverySerializer.new }

  describe 'test an instance of ApiV1WebhooksOutgoingDeliverySerializer' do
    it 'should create an instance of ApiV1WebhooksOutgoingDeliverySerializer' do
      expect(instance).to be_instance_of(BulletTrainTest::ApiV1WebhooksOutgoingDeliverySerializer)
    end
  end
  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
