=begin
#BT Test

#You can update this description in `config/locales/en/application.en.yml`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BtTest::ProjectsTagDataRelationships
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BtTest::ProjectsTagDataRelationships do
  let(:instance) { BtTest::ProjectsTagDataRelationships.new }

  describe 'test an instance of ProjectsTagDataRelationships' do
    it 'should create an instance of ProjectsTagDataRelationships' do
      expect(instance).to be_instance_of(BtTest::ProjectsTagDataRelationships)
    end
  end
  describe 'test attribute "team"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "project"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
