=begin
#BT Test

#You can update this description in `config/locales/en/application.en.yml`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BtTest::TeamDataRelationships
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BtTest::TeamDataRelationships do
  let(:instance) { BtTest::TeamDataRelationships.new }

  describe 'test an instance of TeamDataRelationships' do
    it 'should create an instance of TeamDataRelationships' do
      expect(instance).to be_instance_of(BtTest::TeamDataRelationships)
    end
  end
  describe 'test attribute "scaffolding_absolutely_abstract_creative_concepts"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
