=begin
#Bullet Train Test

#You can update this description in `config/locales/en/application.en.yml`.

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

# Common files
require 'bullet_train_test/api_client'
require 'bullet_train_test/api_error'
require 'bullet_train_test/version'
require 'bullet_train_test/configuration'

# Models
require 'bullet_train_test/models/goal'
require 'bullet_train_test/models/goal_data'
require 'bullet_train_test/models/goal_data_attributes'
require 'bullet_train_test/models/goal_data_relationships'
require 'bullet_train_test/models/me'
require 'bullet_train_test/models/me_data'
require 'bullet_train_test/models/me_data_attributes'
require 'bullet_train_test/models/me_data_relationships'
require 'bullet_train_test/models/me_data_relationships_teams'
require 'bullet_train_test/models/me_data_relationships_teams_data'
require 'bullet_train_test/models/project'
require 'bullet_train_test/models/project_data'
require 'bullet_train_test/models/project_data_attributes'
require 'bullet_train_test/models/projects_tag'
require 'bullet_train_test/models/projects_tag_data'
require 'bullet_train_test/models/projects_tag_data_attributes'
require 'bullet_train_test/models/projects_tag_data_relationships'
require 'bullet_train_test/models/projects_tag_data_relationships_team'
require 'bullet_train_test/models/team'
require 'bullet_train_test/models/team_data'
require 'bullet_train_test/models/team_data_attributes'
require 'bullet_train_test/models/team_data_relationships'

# APIs
require 'bullet_train_test/api/v1_api'

module BulletTrainTest
  class << self
    # Customize default settings for the SDK using block.
    #   BulletTrainTest.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
